# Array insertion and deletion

In [9]:
import array
import numpy as np

array1 = array.array('i', [971,972])
array2 = array.array('i', [1,2,3,5,6,7,9])
#print(np_array2[-1])

#another way array can be defined using other liberary
array3 = np.array([1,5,7,9,9,10,'ab'])

#array insertion
array2.insert(0, 100)
array2.insert(2, 45)
#deleting element from array
array2.remove(45)
array2

array('i', [100, 1, 2, 3, 5, 6, 7, 9])

# Linear search

In [10]:
#linear search
def linearsearch(are, targt):
    for i in range(len(are)):
        if are[i] == targt:
            return i
    return -1
print(linearsearch(array2, 7))

6


# Array Traverse

In [11]:
#array traversal
def traverse(ar):
    are = ar.tolist()
    for i in are:
        print(i)

traverse(array2)

100
1
2
3
5
6
7
9


# Printing, intersting, appending and slicing array

In [12]:
#printing an array
#for i in array2:
  #print(i)

#appending array
array2.append(99)
array2.insert(2,103)
array2.extend(array1)
print(array2)
print(array2[2:4])

array('i', [100, 1, 103, 2, 3, 5, 6, 7, 9, 99, 971, 972])
array('i', [103, 2])


#Multi dimentional array

In [13]:
# Day 1 - 11, 15, 9, 6
# Day 2 - 15, 24, 20, 26

np_array = np.array([[11,15,9,6],[15,24,20,26]])
multi_array = np.insert(np_array, 0, [[1,2, 3, 4]], axis=0)
print(multi_array)

#Access value in multidimentional array

def accessElements(array, rowIndex, colIndex):
  if rowIndex >= len(array) and colIndex >= len(array[0]):
    print('Incorrect Index')
  else:
    print(array[rowIndex][colIndex])

accessElements(multi_array, 1, 2)


[[ 1  2  3  4]
 [11 15  9  6]
 [15 24 20 26]]
9


#Traversing multidimentional array

In [14]:
def traverseArray(array):
  for i in range(len(array)):
    for j in range(len(array[i])):
      print(array[i][j])

traverseArray(multi_array)

1
2
3
4
11
15
9
6
15
24
20
26


#Searching in multidimentional array

In [16]:
def multi_linear_search(array, value):
  for i in range(len(array)):
    for j in range(len(array[i])):
      if array[i][j] == value:
        return 'The value is located at index ' + str(i) + ' ' + str(j)
  return 'The element is not found'

print(multi_linear_search(multi_array, 24))

The value is located at index 2 1


#Deleting row/column from multi dimentional array

In [17]:
print(multi_array)
new_array = np.delete(multi_array, 0, axis=0)
print(new_array)

[[ 1  2  3  4]
 [11 15  9  6]
 [15 24 20 26]]
[[11 15  9  6]
 [15 24 20 26]]
